# Generated by Django 3.2.8 on 2023-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('provinceCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('cityCode', models.IntegerField()),
                ('provinceCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_table',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商家ID')),
                ('merchant_password', models.CharField(max_length=64, null=True, verbose_name='商家密码')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='商家名称')),
                ('merchant_tel', models.IntegerField(verbose_name='商家电话')),
                ('merchant_address', models.CharField(max_length=64, null=True, verbose_name='商家地址')),
                ('merchant_status', models.IntegerField(null=True, verbose_name='商家状态')),
                ('service_type', models.IntegerField(null=True, verbose_name='服务类型ID')),
                ('block', models.IntegerField(null=True, verbose_name='区块ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('merchant_id', models.IntegerField(verbose_name='商家ID')),
                ('order_create_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('order_complete_time', models.DateTimeField(verbose_name='订单完成时间')),
                ('order_type_number', models.IntegerField(verbose_name='需求ID')),
                ('order_status', models.IntegerField(verbose_name='订单状态')),
                ('order_desc', models.CharField(max_length=255, verbose_name='订单描述')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='需求id')),
                ('requirement_name', models.CharField(max_length=64, verbose_name='需求名称')),
                ('requirement_value', models.IntegerField(verbose_name='需求价格')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('districtCode', models.IntegerField()),
                ('cityCode', models.IntegerField()),
                ('provinceCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_password', models.CharField(max_length=64, null=True, verbose_name='用户密码')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('user_tel', models.IntegerField(verbose_name='用户电话')),
                ('user_age', models.IntegerField(verbose_name='用户年龄')),
                ('user_address', models.CharField(max_length=64, verbose_name='用户地址')),
                ('user_address_code', models.IntegerField(verbose_name='地址ID')),
                ('user_birthday', models.DateField(verbose_name='用户生日')),
                ('user_id_card', models.CharField(max_length=18, verbose_name='用户身份证')),
                ('user_urgency', models.IntegerField(verbose_name='用户紧急联系人')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_table',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='工作人员ID')),
                ('worker_name', models.CharField(max_length=64, verbose_name='工作人员姓名')),
                ('worker_level', models.IntegerField(verbose_name='工作人员类型')),
                ('worker_tel', models.IntegerField(verbose_name='工作人员电话')),
            ],
        ),
    ]
