# Generated by Django 3.2.8 on 2023-04-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_requirement_table',
            fields=[
                ('basic_requirement_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='需求大类ID')),
                ('basic_requirement_name', models.CharField(max_length=64, verbose_name='需求大类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_table',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='账单ID')),
                ('order_number', models.CharField(max_length=25, null=True, verbose_name='订单ID')),
                ('account_id', models.IntegerField(verbose_name='账户ID')),
                ('bill_type', models.IntegerField(verbose_name='账单类别')),
                ('bill_time', models.DateTimeField(verbose_name='账单时间')),
                ('bill_money', models.FloatField(null=True, verbose_name='账单金额')),
                ('bill_remark', models.CharField(max_length=255, null=True, verbose_name='账单备注')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('provinceCode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('cityCode', models.CharField(max_length=64)),
                ('provinceCode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_table',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商家ID')),
                ('merchant_password', models.CharField(max_length=25, null=True, verbose_name='商家密码')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='商家名称')),
                ('merchant_tel', models.CharField(max_length=11, verbose_name='商家电话')),
                ('merchant_address', models.CharField(max_length=64, null=True, verbose_name='商家地址')),
                ('merchant_address_code', models.IntegerField(null=True, verbose_name='地址ID')),
                ('merchant_status', models.IntegerField(null=True, verbose_name='商家状态')),
                ('service_type', models.IntegerField(null=True, verbose_name='服务类型ID')),
                ('block', models.IntegerField(null=True, verbose_name='区块ID')),
                ('merchant_assistant_name', models.CharField(max_length=64, null=True, verbose_name='店员姓名')),
                ('merchant_assistant_tel', models.CharField(max_length=11, null=True, verbose_name='店员电话')),
                ('merchant_remark', models.CharField(max_length=255, null=True, verbose_name='商家备注')),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_number', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('user_id', models.CharField(max_length=25, verbose_name='用户ID')),
                ('merchant_id', models.IntegerField(null=True, verbose_name='商家ID')),
                ('order_create_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('order_complete_time', models.DateTimeField(null=True, verbose_name='订单完成时间')),
                ('order_type_number', models.IntegerField(verbose_name='需求ID')),
                ('order_status', models.IntegerField(null=True, verbose_name='订单状态')),
                ('order_price', models.FloatField(null=True, verbose_name='订单价格')),
                ('order_comment', models.CharField(max_length=255, null=True, verbose_name='订单评价')),
                ('order_pay_type', models.IntegerField(null=True, verbose_name='结算类型')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_table',
            fields=[
                ('requirement_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='需求id')),
                ('requirement_name', models.CharField(max_length=64, verbose_name='需求名称')),
                ('requirement_value', models.IntegerField(verbose_name='需求价格')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('districtCode', models.CharField(max_length=64)),
                ('cityCode', models.CharField(max_length=64)),
                ('provinceCode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Urgency_table',
            fields=[
                ('urgency_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='紧急联系人ID')),
                ('user_id', models.CharField(max_length=25, verbose_name='用户ID')),
                ('urgency_tel', models.CharField(max_length=11, verbose_name='紧急联系人电话')),
                ('urgency_name', models.CharField(max_length=64, verbose_name='紧急联系人姓名')),
                ('urgency_relation', models.CharField(max_length=64, null=True, verbose_name='与用户的关系')),
            ],
        ),
        migrations.CreateModel(
            name='User_level_table',
            fields=[
                ('user_level_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户等级ID')),
                ('user_level_price', models.IntegerField(verbose_name='用户等级价格')),
                ('user_level_discount', models.FloatField(verbose_name='用户等级折扣')),
                ('user_level_content', models.CharField(max_length=255, null=True, verbose_name='用户等级内容')),
            ],
        ),
        migrations.CreateModel(
            name='User_level_time_table',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_level_id', models.IntegerField(verbose_name='用户等级ID')),
                ('user_level_deadline', models.DateField(verbose_name='用户等级到期时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('user_sex', models.IntegerField(verbose_name='用户性别')),
                ('user_tel', models.CharField(max_length=11, verbose_name='用户电话')),
                ('user_age', models.IntegerField(verbose_name='用户年龄')),
                ('user_address', models.CharField(max_length=64, verbose_name='用户地址')),
                ('user_address_code', models.IntegerField(null=True, verbose_name='地址ID')),
                ('user_birthday', models.DateField(verbose_name='用户生日')),
                ('user_id_card', models.CharField(max_length=18, verbose_name='用户身份证')),
                ('user_remark', models.CharField(max_length=255, null=True, verbose_name='用户备注')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_table',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='员工ID')),
                ('worker_name', models.CharField(max_length=64, verbose_name='员工姓名')),
                ('worker_type_id', models.IntegerField(verbose_name='员工类型ID')),
                ('worker_tel', models.CharField(max_length=11, verbose_name='员工电话')),
                ('worker_email', models.CharField(max_length=64, verbose_name='员工邮箱')),
                ('worker_sex', models.IntegerField(verbose_name='员工性别')),
                ('worker_age', models.IntegerField(verbose_name='员工年龄')),
                ('worker_birthday', models.DateField(verbose_name='员工生日')),
                ('worker_id_card', models.CharField(max_length=18, verbose_name='员工身份证')),
                ('worker_hiredate', models.DateField(verbose_name='员工入职时间')),
                ('worker_remark', models.CharField(max_length=255, null=True, verbose_name='员工备注')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_type_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type_id', models.IntegerField(verbose_name='员工类型ID')),
                ('worker_type_name', models.CharField(max_length=64, verbose_name='员工类型名称')),
                ('worker_type_remark', models.CharField(max_length=255, null=True, verbose_name='员工类型备注')),
            ],
        ),
    ]
