# Generated by Django 3.2.8 on 2023-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_table',
            name='merchant_assistant_tel',
            field=models.CharField(max_length=11, null=True, verbose_name='店员电话'),
        ),
        migrations.AlterField(
            model_name='merchant_table',
            name='merchant_tel',
            field=models.CharField(max_length=11, verbose_name='商家电话'),
        ),
        migrations.AlterField(
            model_name='urgency_table',
            name='urgency_tel',
            field=models.CharField(max_length=11, verbose_name='紧急联系人电话'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='user_tel',
            field=models.CharField(max_length=11, verbose_name='用户电话'),
        ),
        migrations.AlterField(
            model_name='worker_table',
            name='worker_tel',
            field=models.CharField(max_length=11, verbose_name='员工电话'),
        ),
    ]
